task_name: 'riken'
question_id_pref: ???
question_id_suff: ???
score_id: ???
fold: ???
max_seq_length: 512
data_path: /content/drive/MyDrive/GoogleColab/SA/ShortAnswer/${question_id_pref}/${question_id_suff}_data/${question_id_pref}_${question_id_suff}_fold{fold}