hydra:
  run:
    dir: ${output_dir}
  sweep:
    dir: ${output_dir}/${model.model_type}_${ue.reg_type}/riken
    subdir: ${data.question_id}_${data.prompt_id}_${data.score_id}/fold${data.fold}/id${model.id}

model:
    id: ???
    model_type: ???
    model_name_or_path: 'google/electra-base-discriminator'

ue: ???
training: 
    weight_decay: 0.0
    learning_rate: 5e-5
    per_device_eval_batch_size: 8
    per_device_train_batch_size: 8
    num_train_epochs: 4
    warmup_ratio: 0.1
    seed: 101
    
data:
    task_name: 'riken'
    question_id: 'Y15'
    prompt_id: '2-3_1_5'
    score_id: 'A_Score'
    fold: 0
    subsample_perc: 0.0
    max_seq_length: 512
    validation_subsample: 0.0
    validation_seed: 42
    data_path: '/content/drive/MyDrive/GoogleColab/SA/ShortAnswer'
  
spectralnorm_layer: 'last'
cache_dir: '../workdir/cache/'
output_dir: '../workdir/results/'
seed: fold_${data.fold}
suffix: ''
do_train: True
do_eval: True
do_ue_estimate: True
reset_params: False
repeat: 0

defaults:
  - ue: mc-dpp